id: P8EFD735C
initial_creation_type: input
source_metadata:
  title: Pramāṇa
  parent: 1. Commentaries on the Eighteen Great Treatises
  source: https://sakyalibrary.com
  bases:
    69c6:
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་མདོ་བཞུགས་སོ།།
      author: སློབ་དཔོན་ཕྱོགས་གླང་།
      base_file: 69c6.txt
      order: 1
    76b3:
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པའི་རྒྱན་ཞེས་བྱ་བ།
      author: ནཱ་ལནྡྲའི་མཁན་རབས་གསུམ་པ་དགེ་བ་རྒྱལ་མཚན།
      base_file: 76b3.txt
      order: 2
    cbb8:
      title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་བཞུགས་སོ།།
      author: སློབ་དཔོན་ཆོས་གྲགས།
      base_file: cbb8.txt
      order: 3
    b608:
      title: ཚད་མ་རྣམ་འགྲེལ་གྱི་རྣམ་བཤད་རིགས་པའི་འདོད་འཇོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
      base_file: b608.txt
      order: 4
    006f:
      title: ཚད་མ་རྣམ་འགྲེལ་གྱི་འགྲེལ་པ་རིགས་པའི་མཛོད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: འུ་ཡུག་པ་རིག་པའི་སེངྒེ།
      base_file: 006f.txt
      order: 5
    1b0b:
      title: རྒྱལ་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་རྣམ་པར་བཤད་པ་ཀུན་ཏུ་བཟང་པོའི་འོད་ཟེར་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 1b0b.txt
      order: 6
    da23:
      title: རྒྱས་པའི་བསྟན་བཅོས་ཚད་མ་རྣམ་འགྲེལ་གྱི་ངག་དོན་ཀུན་ཏུ་བཟང་པོའི་ཉི་མ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: da23.txt
      order: 7
    16cd:
      title: རང་དོན་རྗེས་སུ་དཔག་པའི་ལེའུའི་རྣམ་བཤད་ཀུན་བཟང་ཆོས་ཀྱི་རོལ་མཚོ་བྱ་བ་བཞུགས་སོ།།
      author: ཤཱཀ་མཆོག
      base_file: 16cd.txt
      order: 8
    f2dd:
      title: ཚད་མ་གྲུབ་པའི་ལེའུའི་རྣམ་པར་བཤད་པ་བཞུགས་སོ།།
      author: ཤཱཀ་མཆོག
      base_file: f2dd.txt
      order: 9
    f7cb:
      title: མངོན་སུམ་ལེའུའི་རྣམ་པར་བཤད་པ་བཞུགས་སོ།།
      author: ཤཱཀ་མཆོག
      base_file: f7cb.txt
      order: 10
    69cf:
      title: གཞན་དོན་ལེའུའི་རྣམ་པར་བཤད་པ་བཞུགས་སོ།།
      author: ཤཱཀ་མཆོག
      base_file: 69cf.txt
      order: 11
    1fd3:
      title: ཚད་མ་རྣམ་པར་ངེས་པ་བཞུགས་སོ།།
      author: སློབ་དཔོན་ཆོས་གྲགས།
      base_file: 1fd3.txt
      order: 12
    9a7a:
      title: རྣམ་ངེས་ཀྱི་ཊཱིཀྐ་བཞུགས་སོ།།
      author: རྔོག་ལོ་ཙཱ་བ་བློ་ལྡན་ཤེས་རབ།
      base_file: 9a7a.txt
      order: 13
    6df5:
      title: རྣམ་པར་ངེས་པའི་འགྲེལ་བཤད་ཆེན་པོ་རྒྱན་གྱི་མེ་ཏོག་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: བཅོམ་ལྡན་རིག་རལ།
      base_file: 6df5.txt
      order: 14
    071b:
      title: ཚད་མ་རིགས་པའི་གཏེར་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ས་སྐྱ་པཎྜི་ཏ།
      base_file: 071b.txt
      order: 15
    5d3c:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་རང་འགྲེལ་བཞུགས་སོ།།
      author: ས་སྐྱ་པཎྜི་ཏ།
      base_file: 5d3c.txt
      order: 16
    9f81:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དེ་ཁོ་ན་ཉིད་གསལ་བར་བྱེད་པ་རིགས་པའི་འོད་སྟོང་འཕྲོ་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: གཡག་སྟོན་སངས་རྒྱས་དཔལ།
      base_file: 9f81.txt
      order: 17
    6bcc:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་རྣམ་བཤད་ཉི་མའི་སྙིང་པོ་བཞུགས་པའི་དབུ་ཕྱོགས་བྱ་བ་བཞུགས་སོ།།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: 6bcc.txt
      order: 18
    dfa1:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་མཆན་འགྲེལ་སྡེ་བདུན་གསལ་བའི་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: འཇམ་དབྱངས་བློ་གཏེར་དབང་པོ།
      base_file: dfa1.txt
      order: 19
    7b0a:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དཀའ་བའི་གནས་རྣམ་པར་བཤད་པ་སྡེ་བདུན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 7b0a.txt
      order: 20
    00fb:
      title: སྡེ་བདུན་མདོ་དང་བཅས་པའི་དགོངས་པ་ཕྱིན་ཅི་མ་ལོག་པར་འགྲེལ་པ་ཚད་མ་རིགས་པའི་གཏེར་གྱི་དོན་གསལ་བར་བྱེད་པ་ལ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 00fb.txt
      order: 21
    f9c0:
      title: སྡེ་བདུན་མདོ་དང་བཅས་པའི་དགོངས་འགྲེལ་ཚད་མ་རིགས་པའི་གཏེར་གྱི་འགྲེལ་པ་རིགས་ལམ་རབ་གསལ་ལ།
      author: མུས་ཆེན་ཐུགས་རྗེ་དཔལ་བཟང་།
      base_file: f9c0.txt
      order: 22
    fc9f:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་རྒྱན་ལུང་དང་རིགས་པའི་འཁོར་ལོས་ལུགས་ངན་ཕམ་བྱེད་ཅེས་པའམ།
        མིང་གཞན་རྟོག་གེའི་འཁྲུལ་འཇོམས་ཆེན་མོ་པོད་གཉིས་ལས་དང་པོར།
      author: ཤཱཀ་མཆོག
      base_file: fc9f.txt
      order: 23
    3e47:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་རྒྱན་ལུང་དང་རིགས་པའི་འཁོར་ལོས་ལུགས་ངན་ཕམ་བྱེད་ཅེས་པའམ།
        མིང་གཞན་རྟོག་གེའི་འཁྲུལ་འཇོམས་ཆེན་མོ་པོད་གཉིས་པ་ལ།
      author: ཤཱཀ་མཆོག
      base_file: 3e47.txt
      order: 24
    3eb3:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་དགོངས་དོན་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་ངག་གི་དཔལ་སྟེར་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: 3eb3.txt
      order: 25
    90f7:
      title: རྒྱལ་ཚབ་རྗེའི་ཚད་མ་རིགས་པའི་གཏེར་གྱི་རྣམ་བཤད་ལེགས་པར་བཤད་པའི་སྙིང་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: རྒྱལ་ཚབ་རྗེ་དྷརྨ་རིན་ཆེན།
      base_file: 90f7.txt
      order: 26
    9b38:
      title: ཚད་མ་ཀུན་ལས་བཏུས་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པའི་རྒྱན།
      author: ནཱ་ལནྡྲའི་མཁན་རབས་གསུམ་པ་དགེ་བ་རྒྱལ་མཚན།
      base_file: 9b38.txt
      order: 27
    524f:
      title: ཚད་མ་རིགས་པའི་གཏེར་གྱི་ཚར་གཅད་དང་ལྟག་ཆོད་བརྟག་པའི་རྣམ་པར་བཤད་པ་རྩོད་པའི་རྒྱན།
      author: ཐུབ་བསྟན་ཡངས་པ་ཅན་གྱི་མཁན་པོ་དབང་ཕྱུག་དཔལ་བཟང་།
      base_file: 524f.txt
      order: 28
    e9c0:
      title: ཚད་མའི་རྟགས་རིགས་པའི་སྐོར་གཏན་ལ་འབེབས་པར་བྱེད་པ་སྡེ་བདུན་སྒོ་བརྒྱ་འབྱེད་པའི་འཕྲུལ་གྱི་ལྡེའུ་མིག
      author: བློ་གཏེར་དབང་པོ།
      base_file: e9c0.txt
      order: 29
created_at: '2022-04-06T16:12:40.557517'
last_modified_at: '2022-04-06T16:12:40.557543'
